/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IImplementationAuthorityLegacy__factory } from "./IImplementationAuthorityLegacy__factory";
export { LegacyProxy__factory } from "./LegacyProxy__factory";
