/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as legacyIaSol from "./LegacyIA.sol";
export * as legacyProxySol from "./LegacyProxy.sol";
export * as legacyToken352Sol from "./LegacyToken_3_5_2.sol";
