/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IImplementationAuthorityLegacy } from "./IImplementationAuthorityLegacy";
export type { LegacyProxy } from "./LegacyProxy";
