/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { LegacyIA__factory } from "./LegacyIA__factory";
export { OwnableLegacy__factory } from "./OwnableLegacy__factory";
