/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as agent from "./agent";
export type { agent };
import type * as owner from "./owner";
export type { owner };
