/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as v352 from "./v_3_5_2";
export type { v352 };
export type { ClaimIssuerTrick } from "./ClaimIssuerTrick";
export type { MockContract } from "./MockContract";
export type { TestERC20 } from "./TestERC20";
export type { TestUpgradedCountryAllowModule } from "./TestUpgradedCountryAllowModule";
