/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface MockContractInterface extends utils.Interface {
  functions: {
    "identityRegistry()": FunctionFragment;
    "investorCountry(address)": FunctionFragment;
    "setInvestorCountry(uint16)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "identityRegistry"
      | "investorCountry"
      | "setInvestorCountry"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "identityRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "investorCountry",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setInvestorCountry",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "identityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "investorCountry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setInvestorCountry",
    data: BytesLike
  ): Result;

  events: {};
}

export interface MockContract extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MockContractInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    identityRegistry(
      overrides?: CallOverrides
    ): Promise<[string] & { identityRegistry: string }>;

    investorCountry(
      investor: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[number] & { country: number }>;

    setInvestorCountry(
      country: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  identityRegistry(overrides?: CallOverrides): Promise<string>;

  investorCountry(
    investor: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<number>;

  setInvestorCountry(
    country: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    identityRegistry(overrides?: CallOverrides): Promise<string>;

    investorCountry(
      investor: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<number>;

    setInvestorCountry(
      country: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    identityRegistry(overrides?: CallOverrides): Promise<BigNumber>;

    investorCountry(
      investor: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setInvestorCountry(
      country: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    identityRegistry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    investorCountry(
      investor: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setInvestorCountry(
      country: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
