/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export interface AgentManagerInterface extends utils.Interface {
  functions: {
    "addAgentAdmin(address)": FunctionFragment;
    "addComplianceAgent(address)": FunctionFragment;
    "addFreezer(address)": FunctionFragment;
    "addRecoveryAgent(address)": FunctionFragment;
    "addSupplyModifier(address)": FunctionFragment;
    "addTransferManager(address)": FunctionFragment;
    "addWhiteListManager(address)": FunctionFragment;
    "callBatchBurn(address[],uint256[],address)": FunctionFragment;
    "callBatchForcedTransfer(address[],address[],uint256[],address)": FunctionFragment;
    "callBatchFreezePartialTokens(address[],uint256[],address)": FunctionFragment;
    "callBatchMint(address[],uint256[],address)": FunctionFragment;
    "callBatchSetAddressFrozen(address[],bool[],address)": FunctionFragment;
    "callBatchUnfreezePartialTokens(address[],uint256[],address)": FunctionFragment;
    "callBurn(address,uint256,address)": FunctionFragment;
    "callDeleteIdentity(address,address)": FunctionFragment;
    "callForcedTransfer(address,address,uint256,address)": FunctionFragment;
    "callFreezePartialTokens(address,uint256,address)": FunctionFragment;
    "callMint(address,uint256,address)": FunctionFragment;
    "callPause(address)": FunctionFragment;
    "callRecoveryAddress(address,address,address,address)": FunctionFragment;
    "callRegisterIdentity(address,address,uint16,address)": FunctionFragment;
    "callSetAddressFrozen(address,bool,address)": FunctionFragment;
    "callUnfreezePartialTokens(address,uint256,address)": FunctionFragment;
    "callUnpause(address)": FunctionFragment;
    "callUpdateCountry(address,uint16,address)": FunctionFragment;
    "callUpdateIdentity(address,address,address)": FunctionFragment;
    "isAgentAdmin(address)": FunctionFragment;
    "isComplianceAgent(address)": FunctionFragment;
    "isFreezer(address)": FunctionFragment;
    "isRecoveryAgent(address)": FunctionFragment;
    "isSupplyModifier(address)": FunctionFragment;
    "isTransferManager(address)": FunctionFragment;
    "isWhiteListManager(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "removeAgentAdmin(address)": FunctionFragment;
    "removeComplianceAgent(address)": FunctionFragment;
    "removeFreezer(address)": FunctionFragment;
    "removeRecoveryAgent(address)": FunctionFragment;
    "removeSupplyModifier(address)": FunctionFragment;
    "removeTransferManager(address)": FunctionFragment;
    "removeWhiteListManager(address)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "token()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addAgentAdmin"
      | "addComplianceAgent"
      | "addFreezer"
      | "addRecoveryAgent"
      | "addSupplyModifier"
      | "addTransferManager"
      | "addWhiteListManager"
      | "callBatchBurn"
      | "callBatchForcedTransfer"
      | "callBatchFreezePartialTokens"
      | "callBatchMint"
      | "callBatchSetAddressFrozen"
      | "callBatchUnfreezePartialTokens"
      | "callBurn"
      | "callDeleteIdentity"
      | "callForcedTransfer"
      | "callFreezePartialTokens"
      | "callMint"
      | "callPause"
      | "callRecoveryAddress"
      | "callRegisterIdentity"
      | "callSetAddressFrozen"
      | "callUnfreezePartialTokens"
      | "callUnpause"
      | "callUpdateCountry"
      | "callUpdateIdentity"
      | "isAgentAdmin"
      | "isComplianceAgent"
      | "isFreezer"
      | "isRecoveryAgent"
      | "isSupplyModifier"
      | "isTransferManager"
      | "isWhiteListManager"
      | "owner"
      | "removeAgentAdmin"
      | "removeComplianceAgent"
      | "removeFreezer"
      | "removeRecoveryAgent"
      | "removeSupplyModifier"
      | "removeTransferManager"
      | "removeWhiteListManager"
      | "renounceOwnership"
      | "token"
      | "transferOwnership"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addAgentAdmin",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "addComplianceAgent",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "addFreezer",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "addRecoveryAgent",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "addSupplyModifier",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "addTransferManager",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "addWhiteListManager",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "callBatchBurn",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "callBatchForcedTransfer",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "callBatchFreezePartialTokens",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "callBatchMint",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "callBatchSetAddressFrozen",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<boolean>[],
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "callBatchUnfreezePartialTokens",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "callBurn",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "callDeleteIdentity",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "callForcedTransfer",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "callFreezePartialTokens",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "callMint",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "callPause",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "callRecoveryAddress",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "callRegisterIdentity",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "callSetAddressFrozen",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<boolean>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "callUnfreezePartialTokens",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "callUnpause",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "callUpdateCountry",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "callUpdateIdentity",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isAgentAdmin",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isComplianceAgent",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isFreezer",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isRecoveryAgent",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isSupplyModifier",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isTransferManager",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isWhiteListManager",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeAgentAdmin",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeComplianceAgent",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeFreezer",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeRecoveryAgent",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeSupplyModifier",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeTransferManager",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeWhiteListManager",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "addAgentAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addComplianceAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addFreezer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addRecoveryAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addSupplyModifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addTransferManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addWhiteListManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callBatchBurn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callBatchForcedTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callBatchFreezePartialTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callBatchMint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callBatchSetAddressFrozen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callBatchUnfreezePartialTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "callBurn", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "callDeleteIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callForcedTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callFreezePartialTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "callMint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "callPause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "callRecoveryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callRegisterIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callSetAddressFrozen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callUnfreezePartialTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callUnpause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callUpdateCountry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callUpdateIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAgentAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isComplianceAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isFreezer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isRecoveryAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isSupplyModifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTransferManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isWhiteListManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeAgentAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeComplianceAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeFreezer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeRecoveryAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeSupplyModifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeTransferManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeWhiteListManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
    "RoleAdded(address,string)": EventFragment;
    "RoleRemoved(address,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleRemoved"): EventFragment;
}

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface RoleAddedEventObject {
  _agent: string;
  _role: string;
}
export type RoleAddedEvent = TypedEvent<[string, string], RoleAddedEventObject>;

export type RoleAddedEventFilter = TypedEventFilter<RoleAddedEvent>;

export interface RoleRemovedEventObject {
  _agent: string;
  _role: string;
}
export type RoleRemovedEvent = TypedEvent<
  [string, string],
  RoleRemovedEventObject
>;

export type RoleRemovedEventFilter = TypedEventFilter<RoleRemovedEvent>;

export interface AgentManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AgentManagerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addAgentAdmin(
      _agent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addComplianceAgent(
      _agent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addFreezer(
      _agent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addRecoveryAgent(
      _agent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addSupplyModifier(
      _agent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addTransferManager(
      _agent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addWhiteListManager(
      _agent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    callBatchBurn(
      _userAddresses: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    callBatchForcedTransfer(
      _fromList: PromiseOrValue<string>[],
      _toList: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    callBatchFreezePartialTokens(
      _userAddresses: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    callBatchMint(
      _toList: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    callBatchSetAddressFrozen(
      _userAddresses: PromiseOrValue<string>[],
      _freeze: PromiseOrValue<boolean>[],
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    callBatchUnfreezePartialTokens(
      _userAddresses: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    callBurn(
      _userAddress: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    callDeleteIdentity(
      _userAddress: PromiseOrValue<string>,
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    callForcedTransfer(
      _from: PromiseOrValue<string>,
      _to: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    callFreezePartialTokens(
      _userAddress: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    callMint(
      _to: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    callPause(
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    callRecoveryAddress(
      _lostWallet: PromiseOrValue<string>,
      _newWallet: PromiseOrValue<string>,
      _onchainID: PromiseOrValue<string>,
      _managerOnchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    callRegisterIdentity(
      _userAddress: PromiseOrValue<string>,
      _onchainID: PromiseOrValue<string>,
      _country: PromiseOrValue<BigNumberish>,
      _managerOnchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    callSetAddressFrozen(
      _userAddress: PromiseOrValue<string>,
      _freeze: PromiseOrValue<boolean>,
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    callUnfreezePartialTokens(
      _userAddress: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    callUnpause(
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    callUpdateCountry(
      _userAddress: PromiseOrValue<string>,
      _country: PromiseOrValue<BigNumberish>,
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    callUpdateIdentity(
      _userAddress: PromiseOrValue<string>,
      _identity: PromiseOrValue<string>,
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    isAgentAdmin(
      _agent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isComplianceAgent(
      _agent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isFreezer(
      _agent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isRecoveryAgent(
      _agent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isSupplyModifier(
      _agent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isTransferManager(
      _agent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isWhiteListManager(
      _agent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    removeAgentAdmin(
      _agent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeComplianceAgent(
      _agent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeFreezer(
      _agent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeRecoveryAgent(
      _agent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeSupplyModifier(
      _agent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeTransferManager(
      _agent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeWhiteListManager(
      _agent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    token(overrides?: CallOverrides): Promise<[string]>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  addAgentAdmin(
    _agent: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addComplianceAgent(
    _agent: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addFreezer(
    _agent: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addRecoveryAgent(
    _agent: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addSupplyModifier(
    _agent: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addTransferManager(
    _agent: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addWhiteListManager(
    _agent: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callBatchBurn(
    _userAddresses: PromiseOrValue<string>[],
    _amounts: PromiseOrValue<BigNumberish>[],
    _onchainID: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callBatchForcedTransfer(
    _fromList: PromiseOrValue<string>[],
    _toList: PromiseOrValue<string>[],
    _amounts: PromiseOrValue<BigNumberish>[],
    _onchainID: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callBatchFreezePartialTokens(
    _userAddresses: PromiseOrValue<string>[],
    _amounts: PromiseOrValue<BigNumberish>[],
    _onchainID: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callBatchMint(
    _toList: PromiseOrValue<string>[],
    _amounts: PromiseOrValue<BigNumberish>[],
    _onchainID: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callBatchSetAddressFrozen(
    _userAddresses: PromiseOrValue<string>[],
    _freeze: PromiseOrValue<boolean>[],
    _onchainID: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callBatchUnfreezePartialTokens(
    _userAddresses: PromiseOrValue<string>[],
    _amounts: PromiseOrValue<BigNumberish>[],
    _onchainID: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callBurn(
    _userAddress: PromiseOrValue<string>,
    _amount: PromiseOrValue<BigNumberish>,
    _onchainID: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callDeleteIdentity(
    _userAddress: PromiseOrValue<string>,
    _onchainID: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callForcedTransfer(
    _from: PromiseOrValue<string>,
    _to: PromiseOrValue<string>,
    _amount: PromiseOrValue<BigNumberish>,
    _onchainID: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callFreezePartialTokens(
    _userAddress: PromiseOrValue<string>,
    _amount: PromiseOrValue<BigNumberish>,
    _onchainID: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callMint(
    _to: PromiseOrValue<string>,
    _amount: PromiseOrValue<BigNumberish>,
    _onchainID: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callPause(
    _onchainID: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callRecoveryAddress(
    _lostWallet: PromiseOrValue<string>,
    _newWallet: PromiseOrValue<string>,
    _onchainID: PromiseOrValue<string>,
    _managerOnchainID: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callRegisterIdentity(
    _userAddress: PromiseOrValue<string>,
    _onchainID: PromiseOrValue<string>,
    _country: PromiseOrValue<BigNumberish>,
    _managerOnchainID: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callSetAddressFrozen(
    _userAddress: PromiseOrValue<string>,
    _freeze: PromiseOrValue<boolean>,
    _onchainID: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callUnfreezePartialTokens(
    _userAddress: PromiseOrValue<string>,
    _amount: PromiseOrValue<BigNumberish>,
    _onchainID: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callUnpause(
    _onchainID: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callUpdateCountry(
    _userAddress: PromiseOrValue<string>,
    _country: PromiseOrValue<BigNumberish>,
    _onchainID: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callUpdateIdentity(
    _userAddress: PromiseOrValue<string>,
    _identity: PromiseOrValue<string>,
    _onchainID: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  isAgentAdmin(
    _agent: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isComplianceAgent(
    _agent: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isFreezer(
    _agent: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isRecoveryAgent(
    _agent: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isSupplyModifier(
    _agent: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isTransferManager(
    _agent: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isWhiteListManager(
    _agent: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  removeAgentAdmin(
    _agent: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeComplianceAgent(
    _agent: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeFreezer(
    _agent: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeRecoveryAgent(
    _agent: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeSupplyModifier(
    _agent: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeTransferManager(
    _agent: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeWhiteListManager(
    _agent: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  token(overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addAgentAdmin(
      _agent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    addComplianceAgent(
      _agent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    addFreezer(
      _agent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    addRecoveryAgent(
      _agent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    addSupplyModifier(
      _agent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    addTransferManager(
      _agent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    addWhiteListManager(
      _agent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    callBatchBurn(
      _userAddresses: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      _onchainID: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    callBatchForcedTransfer(
      _fromList: PromiseOrValue<string>[],
      _toList: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      _onchainID: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    callBatchFreezePartialTokens(
      _userAddresses: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      _onchainID: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    callBatchMint(
      _toList: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      _onchainID: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    callBatchSetAddressFrozen(
      _userAddresses: PromiseOrValue<string>[],
      _freeze: PromiseOrValue<boolean>[],
      _onchainID: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    callBatchUnfreezePartialTokens(
      _userAddresses: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      _onchainID: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    callBurn(
      _userAddress: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _onchainID: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    callDeleteIdentity(
      _userAddress: PromiseOrValue<string>,
      _onchainID: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    callForcedTransfer(
      _from: PromiseOrValue<string>,
      _to: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _onchainID: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    callFreezePartialTokens(
      _userAddress: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _onchainID: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    callMint(
      _to: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _onchainID: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    callPause(
      _onchainID: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    callRecoveryAddress(
      _lostWallet: PromiseOrValue<string>,
      _newWallet: PromiseOrValue<string>,
      _onchainID: PromiseOrValue<string>,
      _managerOnchainID: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    callRegisterIdentity(
      _userAddress: PromiseOrValue<string>,
      _onchainID: PromiseOrValue<string>,
      _country: PromiseOrValue<BigNumberish>,
      _managerOnchainID: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    callSetAddressFrozen(
      _userAddress: PromiseOrValue<string>,
      _freeze: PromiseOrValue<boolean>,
      _onchainID: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    callUnfreezePartialTokens(
      _userAddress: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _onchainID: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    callUnpause(
      _onchainID: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    callUpdateCountry(
      _userAddress: PromiseOrValue<string>,
      _country: PromiseOrValue<BigNumberish>,
      _onchainID: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    callUpdateIdentity(
      _userAddress: PromiseOrValue<string>,
      _identity: PromiseOrValue<string>,
      _onchainID: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    isAgentAdmin(
      _agent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isComplianceAgent(
      _agent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isFreezer(
      _agent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isRecoveryAgent(
      _agent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isSupplyModifier(
      _agent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isTransferManager(
      _agent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isWhiteListManager(
      _agent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    removeAgentAdmin(
      _agent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeComplianceAgent(
      _agent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeFreezer(
      _agent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeRecoveryAgent(
      _agent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeSupplyModifier(
      _agent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeTransferManager(
      _agent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeWhiteListManager(
      _agent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    token(overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "RoleAdded(address,string)"(
      _agent?: PromiseOrValue<string> | null,
      _role?: null
    ): RoleAddedEventFilter;
    RoleAdded(
      _agent?: PromiseOrValue<string> | null,
      _role?: null
    ): RoleAddedEventFilter;

    "RoleRemoved(address,string)"(
      _agent?: PromiseOrValue<string> | null,
      _role?: null
    ): RoleRemovedEventFilter;
    RoleRemoved(
      _agent?: PromiseOrValue<string> | null,
      _role?: null
    ): RoleRemovedEventFilter;
  };

  estimateGas: {
    addAgentAdmin(
      _agent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addComplianceAgent(
      _agent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addFreezer(
      _agent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addRecoveryAgent(
      _agent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addSupplyModifier(
      _agent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addTransferManager(
      _agent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addWhiteListManager(
      _agent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    callBatchBurn(
      _userAddresses: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    callBatchForcedTransfer(
      _fromList: PromiseOrValue<string>[],
      _toList: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    callBatchFreezePartialTokens(
      _userAddresses: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    callBatchMint(
      _toList: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    callBatchSetAddressFrozen(
      _userAddresses: PromiseOrValue<string>[],
      _freeze: PromiseOrValue<boolean>[],
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    callBatchUnfreezePartialTokens(
      _userAddresses: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    callBurn(
      _userAddress: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    callDeleteIdentity(
      _userAddress: PromiseOrValue<string>,
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    callForcedTransfer(
      _from: PromiseOrValue<string>,
      _to: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    callFreezePartialTokens(
      _userAddress: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    callMint(
      _to: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    callPause(
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    callRecoveryAddress(
      _lostWallet: PromiseOrValue<string>,
      _newWallet: PromiseOrValue<string>,
      _onchainID: PromiseOrValue<string>,
      _managerOnchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    callRegisterIdentity(
      _userAddress: PromiseOrValue<string>,
      _onchainID: PromiseOrValue<string>,
      _country: PromiseOrValue<BigNumberish>,
      _managerOnchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    callSetAddressFrozen(
      _userAddress: PromiseOrValue<string>,
      _freeze: PromiseOrValue<boolean>,
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    callUnfreezePartialTokens(
      _userAddress: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    callUnpause(
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    callUpdateCountry(
      _userAddress: PromiseOrValue<string>,
      _country: PromiseOrValue<BigNumberish>,
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    callUpdateIdentity(
      _userAddress: PromiseOrValue<string>,
      _identity: PromiseOrValue<string>,
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    isAgentAdmin(
      _agent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isComplianceAgent(
      _agent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isFreezer(
      _agent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isRecoveryAgent(
      _agent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isSupplyModifier(
      _agent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isTransferManager(
      _agent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isWhiteListManager(
      _agent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    removeAgentAdmin(
      _agent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeComplianceAgent(
      _agent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeFreezer(
      _agent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeRecoveryAgent(
      _agent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeSupplyModifier(
      _agent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeTransferManager(
      _agent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeWhiteListManager(
      _agent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    token(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addAgentAdmin(
      _agent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addComplianceAgent(
      _agent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addFreezer(
      _agent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addRecoveryAgent(
      _agent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addSupplyModifier(
      _agent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addTransferManager(
      _agent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addWhiteListManager(
      _agent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    callBatchBurn(
      _userAddresses: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    callBatchForcedTransfer(
      _fromList: PromiseOrValue<string>[],
      _toList: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    callBatchFreezePartialTokens(
      _userAddresses: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    callBatchMint(
      _toList: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    callBatchSetAddressFrozen(
      _userAddresses: PromiseOrValue<string>[],
      _freeze: PromiseOrValue<boolean>[],
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    callBatchUnfreezePartialTokens(
      _userAddresses: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    callBurn(
      _userAddress: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    callDeleteIdentity(
      _userAddress: PromiseOrValue<string>,
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    callForcedTransfer(
      _from: PromiseOrValue<string>,
      _to: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    callFreezePartialTokens(
      _userAddress: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    callMint(
      _to: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    callPause(
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    callRecoveryAddress(
      _lostWallet: PromiseOrValue<string>,
      _newWallet: PromiseOrValue<string>,
      _onchainID: PromiseOrValue<string>,
      _managerOnchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    callRegisterIdentity(
      _userAddress: PromiseOrValue<string>,
      _onchainID: PromiseOrValue<string>,
      _country: PromiseOrValue<BigNumberish>,
      _managerOnchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    callSetAddressFrozen(
      _userAddress: PromiseOrValue<string>,
      _freeze: PromiseOrValue<boolean>,
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    callUnfreezePartialTokens(
      _userAddress: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    callUnpause(
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    callUpdateCountry(
      _userAddress: PromiseOrValue<string>,
      _country: PromiseOrValue<BigNumberish>,
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    callUpdateIdentity(
      _userAddress: PromiseOrValue<string>,
      _identity: PromiseOrValue<string>,
      _onchainID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    isAgentAdmin(
      _agent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isComplianceAgent(
      _agent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isFreezer(
      _agent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isRecoveryAgent(
      _agent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isSupplyModifier(
      _agent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isTransferManager(
      _agent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isWhiteListManager(
      _agent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    removeAgentAdmin(
      _agent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeComplianceAgent(
      _agent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeFreezer(
      _agent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeRecoveryAgent(
      _agent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeSupplyModifier(
      _agent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeTransferManager(
      _agent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeWhiteListManager(
      _agent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    token(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
