/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AgentRoleUpgradeableLegacy__factory } from "./AgentRoleUpgradeableLegacy__factory";
export { IClaimIssuerLegacy__factory } from "./IClaimIssuerLegacy__factory";
export { IClaimTopicsRegistryLegacy__factory } from "./IClaimTopicsRegistryLegacy__factory";
export { IComplianceLegacy__factory } from "./IComplianceLegacy__factory";
export { IERC20Legacy__factory } from "./IERC20Legacy__factory";
export { IERC734Legacy__factory } from "./IERC734Legacy__factory";
export { IERC735Legacy__factory } from "./IERC735Legacy__factory";
export { IIdentityRegistryLegacy__factory } from "./IIdentityRegistryLegacy__factory";
export { IIdentityRegistryStorageLegacy__factory } from "./IIdentityRegistryStorageLegacy__factory";
export { ITokenLegacy__factory } from "./ITokenLegacy__factory";
export { ITrustedIssuersRegistryLegacy__factory } from "./ITrustedIssuersRegistryLegacy__factory";
export { LegacyIIdentity__factory } from "./LegacyIIdentity__factory";
export { LegacyToken_3_5_2__factory } from "./LegacyToken_3_5_2__factory";
export { OwnableUpgradeableLegacy__factory } from "./OwnableUpgradeableLegacy__factory";
