/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as features from "./features";
export type { features };
import type * as test from "./test";
export type { test };
export type { BasicCompliance } from "./BasicCompliance";
export type { DefaultCompliance } from "./DefaultCompliance";
export type { ICompliance } from "./ICompliance";
