/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as legacyIaSol from "./LegacyIA.sol";
export type { legacyIaSol };
import type * as legacyProxySol from "./LegacyProxy.sol";
export type { legacyProxySol };
import type * as legacyToken352Sol from "./LegacyToken_3_5_2.sol";
export type { legacyToken352Sol };
