/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  ClaimIssuerTrick,
  ClaimIssuerTrickInterface,
} from "../../../contracts/_testContracts/ClaimIssuerTrick";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_identity",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "claimTopic",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "sig",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "isClaimValid",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506101c6806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063c0969a6e14610030575b600080fd5b61004361003e3660046100f8565b610057565b604051901515815260200160405180910390f35b60006001600160a01b0387163303610071575060016100a5565b60405162461bcd60e51b815260206004820152600560248201526422a92927a960d91b604482015260640160405180910390fd5b9695505050505050565b60008083601f8401126100c157600080fd5b50813567ffffffffffffffff8111156100d957600080fd5b6020830191508360208285010111156100f157600080fd5b9250929050565b6000806000806000806080878903121561011157600080fd5b86356001600160a01b038116811461012857600080fd5b955060208701359450604087013567ffffffffffffffff8082111561014c57600080fd5b6101588a838b016100af565b9096509450606089013591508082111561017157600080fd5b5061017e89828a016100af565b979a969950949750929593949250505056fea264697066735822122060e8e4ec21a9e00b936e7de088770fdd7d6f99a0546cc53dccc341bceed045e064736f6c63430008110033";

type ClaimIssuerTrickConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ClaimIssuerTrickConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ClaimIssuerTrick__factory extends ContractFactory {
  constructor(...args: ClaimIssuerTrickConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ClaimIssuerTrick> {
    return super.deploy(overrides || {}) as Promise<ClaimIssuerTrick>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): ClaimIssuerTrick {
    return super.attach(address) as ClaimIssuerTrick;
  }
  override connect(signer: Signer): ClaimIssuerTrick__factory {
    return super.connect(signer) as ClaimIssuerTrick__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ClaimIssuerTrickInterface {
    return new utils.Interface(_abi) as ClaimIssuerTrickInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ClaimIssuerTrick {
    return new Contract(address, _abi, signerOrProvider) as ClaimIssuerTrick;
  }
}
