/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DVATransferManager } from "./DVATransferManager";
export type { IDVATransferManager } from "./IDVATransferManager";
