/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as v352 from "./v_3_5_2";
export { ClaimIssuerTrick__factory } from "./ClaimIssuerTrick__factory";
export { MockContract__factory } from "./MockContract__factory";
export { TestERC20__factory } from "./TestERC20__factory";
export { TestUpgradedCountryAllowModule__factory } from "./TestUpgradedCountryAllowModule__factory";
